-- Seed 50 Most Common Gym Exercises
INSERT INTO exercises (name, is_system_default) VALUES
('Supino Reto com Barra', true),
('Supino Inclinado com Halteres', true),
('Crossover', true),
('Crucifixo Reto', true),
('Peck Deck (Voador)', true),
('Supino Declinado com Barra', true),
('Flexão de Braços', true),
('Puxada Frontal Alta', true),
('Remada Curvada com Barra', true),
('Remada Sentada (Triângulo)', true),
('Puxada com Triângulo', true),
('Remada Unilateral (Serrote)', true),
('Pull Down', true),
('Levantamento Terra', true),
('Desenvolvimento com Halteres', true),
('Elevação Lateral', true),
('Elevação Frontal', true),
('Encolhimento de Ombros', true),
('Desenvolvimento Militar', true),
('Crucifixo Inverso', true),
('Agachamento Livre com Barra', true),
('Leg Press 45', true),
('Cadeira Extensora', true),
('Mesa Flexora', true),
('Afundo (Passada)', true),
('Cadeira Adutora', true),
('Cadeira Abdutora', true),
('Stiff', true),
('Panturrilha Sentado', true),
('Panturrilha em Pé', true),
('Rosca Direta com Barra', true),
('Rosca Alternada com Halteres', true),
('Rosca Martelo', true),
('Rosca Concentrada', true),
('Rosca Scott', true),
('Tríceps Pulley', true),
('Tríceps Corda', true),
('Tríceps Testa', true),
('Tríceps Coice', true),
('Mergulho (Dips)', true),
('Abdominal Supra', true),
('Abdominal Infra', true),
('Prancha Isométrica', true),
('Abdominal Roda', true),
('Hiperextensão Lombar', true),
('Hack Squat', true),
('Cadeira Flexora', true),
('Desenvolvimento Máquina', true),
('Remada Cavalinho', true),
('Face Pull', true)
ON CONFLICT (name) DO NOTHING;
